#!/bin/sh
domain=`hostname -d`
host=$1
cd /var/condor
sed -i.bak -e "s/<host>/$host/" -e "s/<domain>/$domain/" condor_config.worker
ln -sf condor_config.worker condor_config.local
/usr/local/condor/sbin/condor_master
